version: '3.7'
services:
  
  matomo-app:
    image: ryanwclark/matomo
    container_name: matomo-app
    links:
    - matomo-db
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:matomo.example.com
    - traefik.port=80
    - traefik.protocol=http
    - traefik.docker.network=proxy
    - traefik.backend=matomo-app
    volumes:
    - ./data:/www/html
    - ./logs:/www/logs
    environment:
    - ZABBIX_HOSTNAME=matomo-app

    - DB_HOST=matomo-db
    - DB_NAME=matomo
    - DB_USER=matomo
    - DB_PASS=userpassword

    - CRON_PERIOD=60
    networks:
    - proxy
    - services
    restart: always
    
  matomo-db:
    image: ryanwclark/mariadb
    container_name: matomo-db
    volumes:
    - /var/local/db/matomo:/var/lib/mysql
    environment:
    - ROOT_PASS=password
    - DB_NAME=matomo
    - DB_USER=matomo
    - DB_PASS=userpassword

    - ZABBIX_HOSTNAME=matomo-db
    networks:
    - internal
    - services
    restart: always

  matomo-db-redis:
    image: ryanwclark/redis:latest
    container_name: matomo-db-redis
    volumes:
    - ./redis:/data:Z
    environment:
    - ZABBIX_HOSTNAME=matomo-db-redis
    networks:
    - internal
    - services
    restart: always
    
  matomo-db-backup:
    image: ryanwclark/db-backup
    container_name: matomo-db-backup
    links:
    - matomo-db
    volumes:
    - ./dbbackup:/backup
    environment:
    - ZABBIX_HOSTNAME=matomo-db-backup
    - DB_HOST=matomo-db
    - DB_TYPE=mysql
    - DB_NAME=matomo
    - DB_USER=matomo
    - DB_PASSWORD=userpassword
    - DB_DUMP_FREQ=1440
    - DB_DUMP_BEGIN=0000
    - DB_CLEANUP_TIME=8640
    - MD5=TRUE
    - COMPRESSION=BZ
    networks:
    - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
